### PR TITLE
docs(no-unsed): fix typo

### PR DESCRIPTION
**Pull request by ikatyang**
https://github.com/ajafff/tslint-consistent-codestyle/blob/d2454ce/rules/noUnusedRule.ts#L9

### CODE REVIEW

**Comment by ikatyang** [comment]
Uh.. I'm just fixing the typo in the docs, not code, so it won't break users.

**Comment by ajafff** [comment]
I know, but it's no typo. The options are really named `unused-function-expression-name` and `unused-class-expression-name`

**Comment by ikatyang** [comment]
but it's `no-unused-class-expression-name` in your docs... so I want to fix it

**Comment by ikatyang** [comment]
I'm just a little confused why the docs said `no-unused-class-expression-name`, but it actually works with `unused-class-expression-name`, sorry for bothering you so much. 😅

**Comment by ajafff** [comment]
Ah, now I see. Your fix is correct. Sorry, I was wrong. I thought you wanted to add the prefix ... maybe I need more sleep.

Thank your for your patience. I fixed it on master.

**Pull request closed without merging**
